version: '2'
services:
  db:
    image: mysql:8
    container_name: laravel_my_mysql
    environment:
      MYSQL_DATABASE: skillup
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  php:
    image: webdevops/php:7.4
    container_name: laravel_my_php
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 5000M
      PHP_POST_MAX_SIZE: 5000M
    volumes:
      - "./:/laravel"
    working_dir: '/laravel'
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: laravel_my_nginx
    environment:
      WEB_DOCUMENT_ROOT: /laravel/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/laravel"
    ports:
      - "8000:80"

